library(circlize)

# R 3.6

# OBJECTIVE
# Plot interactions of pair of genes from table generated by get-genes-from-positions.py
# Circular plot with "circlize".
# Jpg file.
# See https://jokergoo.github.io/circlize_book/book/circular-layout.html#coordinate-transformation

# ARGUMENTS
# --input_path       Path to read input files.
# --gene_pairs_file    Pairs of genes file:
#                       position_1, start_pos_1, end_pos_1, gene_type_1, gene_name_1,
#                       product_1, protein_id_1, note_1,
#                       position_2, start_pos_2, end_pos_2, gene_type_2, gene_name_2,
#                       product_2, protein_id_2, note_2,
#                       distance, label, score
#                       Tab-separated-value file.
# --output_path      Path to place output files.
# --output_file      Output plot file. Jpg file.
# --threshold        Threshold for score X.XX

# OUTPUT
# 1) Output file:
#   Circular plot with interactions (jpg).

# RUN:
# Rscript circular_plot.R
# /home/user/my_path/
# genes_highly_associated.csv
# /home/user/my_path/
# circular_genes_highly_associated.jpg
# 1.00
# RUN:
# Rscript circular_plot.R /home/user/my_path genes_highly_associated.csv /home/user/my_path circular_genes_highly_associated.jpg 1.00

print("")
print('-------------------------------- RUNNING --------------------------------')
print("")

args = commandArgs(trailingOnly=TRUE)

if (length(args)<2) {
  stop("At least two argument must be supplied (input_path and gene_pairs_file).n", call.=FALSE)
} else if (length(args)==2) {
  # default output path and output file
  args[3] = args[1]
  args[4] = "circular_out.jpg"
  args[5] = "0.00"
}

input_path = args[1]
input_file = args[2]
output_path = args[3]
output_file = args[4]

if (is.na(args[5])){
  threshold = 0.00
} else {
  threshold = as.numeric(args[5])
}


print('-------------------------------- PARAMETERS --------------------------------')
print(paste("Input path:", input_path))
print(paste("Input file:", input_file))
print(paste("Output path:", output_path))
print(paste("Output file:", output_file))
print(paste("Threshold:", threshold))

print('-------------------------------- READING POSITION FILE --------------------------------')
# Read input table with gene interactions
df <- read.csv(paste(input_path, input_file, sep = ""), header = TRUE,sep = "\t", stringsAsFactors=FALSE)
print(paste("Gene interactions read:", nrow(df)))

# Filter rows for score threshold
if (threshold > 0){
  print(paste("   Threshold supplied: ", threshold))
  df <- df[df$score >= threshold, ]
  print(paste("   Gene interactions after threshold:", nrow(df)))
}

#stop("Exit")

print('-------------------------------- REMOVE MISSING POSITIONS (NON GENE NAME) --------------------------------')
# Remove empty gene_name_1 or gene_name_2
df = subset(df, gene_name_1 != "")
df = subset(df, gene_name_2 != "")
print(paste("   Gene interactions after remmove missing positions:", nrow(df)))

# Create dataframe of genes
# gene start end 
genes_1 <- df[c("gene_name_1", "start_pos_1", "end_pos_1")]
genes_2 <- df[c("gene_name_2", "start_pos_2", "end_pos_2")]
names(genes_2)[names(genes_2)=="gene_name_2"] <- "gene_name_1"
names(genes_2)[names(genes_2)=="start_pos_2"] <- "start_pos_1"
names(genes_2)[names(genes_2)=="end_pos_2"] <- "end_pos_1"
genes <- data.frame()
genes <- rbind(genes_1, genes_2)

# Remove duplicated genes
genes <- unique(genes)
print(paste("   Unique genes:", nrow(genes)))

# Factors for plot
factors <- genes[, "gene_name_1"]
# Range of positions for plot
xlim = data.matrix(genes[, c("start_pos_1", "end_pos_1")])

# Colors
my_colors <- heat.colors(length(factors))
#my_colors <- terrain.colors(length(factors))
#my_colors <- topo.colors(length(factors))
hash_colors<-data.frame(x=factors, val=my_colors)

# Clean parameters and internal variables for circos plot
circos.clear()
# File to save
jpeg(file=paste(output_path, output_file, sep = ""), width = 1200, height = 1000, res = 200)
par(mar=c(0.5,0.5,0.5,0.5))
circos.par(cell.padding = c(0.02, 0, 0.02, 0))
# Initialize plot
circos.initialize(factors = factors, xlim = xlim)
# Plot genes as sectors using gene start and end positions as range
circos.track(factors = factors, ylim = c(0, 1), track.margin=c(0,0.3), bg.col = my_colors,
             panel.fun = function(x, y) {
               circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2] + uy(10, "mm"), 
                           CELL_META$sector.index, facing = "clockwise", cex = 0.6, niceFacing = TRUE)
               circos.axis(labels.cex = 0.3)
             })
# Add links between sectors using gene interactions
# Getting interactions from input data
interactions <- df[c("gene_name_1", "position_1", "gene_name_2", "position_2")]

# For each interaction add a link in plot
for (row in 1:nrow(interactions)) {
  g1 <- interactions[row, "gene_name_1"]
  p1 <- interactions[row, "position_1"]
  g2 <- interactions[row, "gene_name_2"]
  p2 <- interactions[row, "position_2"]
  c <- as.character(hash_colors[hash_colors$x == as.character(g1), "val"])
  circos.link(g1, p1, g2, p2, col = c)
}

dev.off()

print('-------------------------------- DONE! --------------------------------')